[workspace]
members = ["morloc-deps", "mim-env", "mim"]
resolver = "2"

[workspace.package]
version = "0.27.1"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "raw_value"] }
nix = { version = "0.29", features = ["signal", "socket", "mman", "process", "fs", "user"] }
clap = { version = "4", features = ["derive", "wrap_help"] }
thiserror = "2"
sha2 = "0.10"

[profile.release]
opt-level = 2
lto = "thin"
panic = "unwind"

[profile.dev]
panic = "unwind"
