//! FHS sandbox for the native backend on hosts without a standard FHS (NixOS).
//!
//! Conda binaries bake the glibc dynamic loader at `/lib64/ld-linux-*`, a path
//! NixOS does not have, so they cannot launch directly. Rather than rewrite the
//! whole toolchain to nixpkgs (a large, separately-maintained mapping), we supply
//! the missing FHS at runtime with a `nix`-built `buildFHSEnv` sandbox
//! (bubblewrap): inside it `/usr`, `/lib`, `/lib64`, and a base set of system
//! libraries exist FHS-style, so unmodified conda ELFs load. pixi still solves
//! everything; the sandbox only provides the loader + base libs.
//!
//! The sandbox is a single shared launcher (`bin/morloc-fhs`), built once per
//! host under `<data_dir>/fhs/` and reused across environments (its contents are
//! environment-independent). It is invoked as `morloc-fhs -c "<shell>"`, which
//! runs `bash -c "<shell>"` inside the namespace.
//!
//! Namespace shape (relied on by the native run/serve seam):
//! - NET must stay shared with the host, so a served nexus binds its TCP port on
//!   the host loopback where clients reach it. `buildFHSEnv` does not unshare net,
//!   so this holds; the sandbox adds nothing that would change it.
//! - Serve TEARDOWN is robust regardless of whether pid is unshared: the launcher
//!   is `setsid`-detached and tracked as the serve handle, and `stop` escalates
//!   SIGTERM -> SIGKILL to it; killing the launcher (bwrap) tears down everything
//!   it supervises (as pid-1 of an unshared pid ns, or as the group leader of a
//!   shared one). Graceful SHM cleanup on SIGTERM is best-effort either way.

use crate::config;
use crate::error::{ManagerError, Result};
use crate::types::Scope;
use std::path::{Path, PathBuf};
use std::process::Command;

/// nixpkgs branch used to build the sandbox, overridable with `MORLOC_FHS_NIXPKGS`
/// (a tarball URL or a local path). The default tracks a stable release branch so
/// `buildFHSEnv` and the named packages resolve; a user on a different nixpkgs can
/// point this at their own. Pinned to a branch (not a bare commit) so the URL
/// always resolves; pin to an exact commit + `sha256` here for full hermeticity.
const DEFAULT_NIXPKGS_URL: &str =
    "https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-25.05.tar.gz";

/// The generated `fhs.nix`. `targetPkgs` is the base-system set conda ELFs and the
/// prebuilt (glibc-dynamic) morloc compiler assume present -- conda ships its own
/// libs under `$CONDA_PREFIX`, so this is only the floor. Deliberately NO wrapped
/// `gcc`/`stdenv.cc`: a `/usr/bin/gcc` would shadow the conda toolchain. Only
/// `gcc-unwrapped.lib` (libstdc++/libgcc runtime, no driver) is included.
fn fhs_nix(nixpkgs_url: &str, host_terminfo: Option<&str>) -> String {
    // The host's per-terminal terminfo entries (e.g. xterm-kitty, shipped OUTSIDE
    // ncurses) live under a /run/current-system symlink into a read-only /nix/store
    // path. Reference that resolved store path directly in TERMINFO_DIRS -- it is
    // already visible in the sandbox via the /nix/store mount -- rather than
    // bind-mounting the /run/current-system path, whose symlinked, read-only parents
    // bwrap cannot create a mountpoint under ("Can't mkdir parents ...").
    let terminfo_dirs = match host_terminfo {
        Some(p) => format!("{p}:/usr/share/terminfo"),
        None => "/usr/share/terminfo".to_string(),
    };
    format!(
        r#"# Generated by mim. Regenerated when missing.
# Override the nixpkgs source with the MORLOC_FHS_NIXPKGS environment variable.
let
  nixpkgsSrc = builtins.fetchTarball {{ url = "{url}"; }};
  pkgs = import nixpkgsSrc {{ }};
in
pkgs.buildFHSEnv {{
  name = "morloc-fhs";
  # Base-system libraries conda ELFs + the prebuilt morloc compiler expect at FHS
  # paths. conda supplies the rest under $CONDA_PREFIX. libffi = GHC RTS in the
  # compiler; libxcrypt-legacy = libcrypt.so.1 for conda CPython.
  #
  # The second group is the bare build/activation TOOLCHAIN the sandboxed steps
  # shell out to by name: `awk` runs first in every activation capture (env dump);
  # `morloc init` invokes `git` (cpp init.sh clones mlccpptypes), `make`, and
  # `pkg-config`; the coreutils/sed/grep/find/tar/gzip set backs the shell glue.
  # buildFHSEnv's base may already carry some of these, but listing them makes the
  # sandbox self-sufficient instead of depending on that base staying stable.
  targetPkgs = pkgs: (with pkgs; [
    glibc
    gcc-unwrapped.lib
    zlib
    gmp
    libffi
    libxcrypt-legacy
    ncurses
    openssl
    bzip2
    xz
    readline
    expat
    util-linux
    coreutils
    bashInteractive
    # build/activation toolchain invoked by name inside the sandbox
    gawk
    git
    gnumake
    pkg-config
    gnused
    gnugrep
    findutils
    gnutar
    gzip
  ]);
  runScript = "bash";
  # ncurses tools (clear/tput/reset) read a terminfo database. Two dirs are put on
  # the search path: the sandbox's own ncurses terminfo (linked under /usr, the
  # standard entries), and the host's system terminfo. The host dir matters because
  # per-terminal entries ship OUTSIDE ncurses -- e.g. `xterm-kitty` comes from the
  # kitty package -- so the user's actual $TERM is often absent from the ncurses set.
  # The host dir is its resolved /nix/store realpath (see fhs_nix), already visible
  # in the sandbox via the /nix/store mount, so it needs no bind.
  # Sourced on every `morloc-fhs -c` entry, so shell, run, and serve agree.
  profile = ''
    export TERMINFO_DIRS={terminfo}
  '';
  # Share the host /dev/shm so morloc's name-based shared-memory volumes have the
  # host's (large) tmpfs rather than a small sandbox default. buildFHSEnv leaves
  # pid + net shared, so host PIDs / process groups and loopback ports work.
  extraBwrapArgs = [
    "--bind" "/dev/shm" "/dev/shm"
  ];
}}
"#,
        url = nixpkgs_url,
        terminfo = terminfo_dirs
    )
}

/// Directory holding the generated expression + the build's out-link.
fn fhs_dir(scope: Scope) -> PathBuf {
    config::data_dir(scope).join("fhs")
}

/// Path to the sandbox launcher for `scope`, whether or not it has been built.
fn wrapper_path(scope: Scope) -> PathBuf {
    fhs_dir(scope).join("result").join("bin").join("morloc-fhs")
}

/// Resolve a `nix` executable to invoke, honoring the standard NixOS locations
/// before PATH so this works even when PATH is minimal.
fn nix_bin() -> PathBuf {
    for p in [
        "/run/current-system/sw/bin/nix-build",
        "/nix/var/nix/profiles/default/bin/nix-build",
    ] {
        if Path::new(p).exists() {
            return PathBuf::from(p);
        }
    }
    PathBuf::from("nix-build")
}

/// Ensure the shared FHS sandbox is built and return its launcher path.
/// Idempotent: an already-built launcher is reused ONLY when the `fhs.nix` it was
/// built from still matches what we would generate now -- so a changed
/// `MORLOC_FHS_NIXPKGS`, or an mim upgrade with a new `targetPkgs`, forces a
/// rebuild instead of silently reusing a stale sandbox. The out-link under
/// `<data_dir>/fhs/result` is an indirect nix GC root, so the sandbox survives
/// `nix-collect-garbage`.
pub fn ensure_fhs_wrapper(scope: Scope) -> Result<PathBuf> {
    let dir = fhs_dir(scope);
    let wrapper = wrapper_path(scope);
    let nix_file = dir.join("fhs.nix");
    let nixpkgs_url =
        std::env::var("MORLOC_FHS_NIXPKGS").unwrap_or_else(|_| DEFAULT_NIXPKGS_URL.to_string());
    // Resolve the host terminfo symlink to its /nix/store realpath at generation
    // time (a system-generation change alters it -> the expression changes -> the
    // sandbox rebuilds). Absent/unresolvable -> the sandbox's own ncurses set only.
    let host_terminfo = std::fs::canonicalize("/run/current-system/sw/share/terminfo")
        .ok()
        .map(|p| p.display().to_string());
    let desired = fhs_nix(&nixpkgs_url, host_terminfo.as_deref());

    // Reuse when the launcher resolves through the out-link AND the expression it
    // was built from is unchanged.
    if wrapper.exists()
        && std::fs::read_to_string(&nix_file).map(|c| c == desired).unwrap_or(false)
    {
        return Ok(wrapper);
    }

    std::fs::create_dir_all(&dir).map_err(|e| {
        ManagerError::EnvError(format!("cannot create {}: {e}", dir.display()))
    })?;
    std::fs::write(&nix_file, &desired).map_err(|e| {
        ManagerError::EnvError(format!("cannot write {}: {e}", nix_file.display()))
    })?;

    eprintln!("Building the FHS sandbox with nix (first time on this host; may take a while)...");
    let out_link = dir.join("result");
    let status = Command::new(nix_bin())
        .arg(&nix_file)
        .arg("-o")
        .arg(&out_link)
        .status()
        .map_err(|e| {
            ManagerError::EnvError(format!(
                "could not run nix-build for the FHS sandbox ({e}). NixOS native support \
                 needs `nix` on this host."
            ))
        })?;
    if !status.success() {
        return Err(ManagerError::EnvError(format!(
            "nix-build of the FHS sandbox failed (see output above). The generated \
             expression is at {}; set MORLOC_FHS_NIXPKGS to a nixpkgs your host can \
             evaluate, or use a container backend.",
            nix_file.display()
        )));
    }
    if !wrapper.exists() {
        return Err(ManagerError::EnvError(format!(
            "the FHS sandbox built but its launcher is missing at {}",
            wrapper.display()
        )));
    }
    Ok(wrapper)
}
